include: '.variables.yml' 

stages:
    - build
    - package
    
.windows_build_template: &windows_build
    stage: build
    script:
        - set PATH=%TOOLS%;%PATH% 
        - qmake CONFIG+=release BUILD_FLAGS="program unittests" 
        - jom -j24
        - strip libqticsneocanbus.dll 

    artifacts:
        name: "libqticsneocanbus_dll_Qt%QT_VER%_Rev%REVISION%_Build%CI_PIPELINE_ID%"
        paths:
        - libqticsneocanbus.dll 
        expire_in: 2 days 
       

build_qt5.15.2_MinGw_32:
    <<: *windows_build 
    tags: ["mingw_qt5.15.2"]


 
        
