variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
stages:
    - build
    - package
    
.windows_build_template: &windows_build
    stage: build
    script:
        - set PATH=%TOOLS%;%PATH% 
        - qmake -r CONFIG+=release
        - jom -j56        

    artifacts:
        name: "qticsneocanbus_dll_%CI_RUNNER_TAGS%_Build%CI_PIPELINE_ID%"
        paths:
        - plugins/canbus/*.dll 
        expire_in: 2 days 
       

build_qt5.15.2_MinGw_32:    
    <<: *windows_build 
    tags: ["mingw_qt5.15.2"]


 
        
